# Generated by Django 3.2.11 on 2022-08-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('twitter', models.URLField(blank=True, max_length=10000, null=True)),
                ('facebook', models.URLField(blank=True, max_length=10000, null=True)),
                ('instagram', models.URLField(blank=True, max_length=10000, null=True)),
                ('linked_in', models.URLField(blank=True, max_length=10000, null=True)),
                ('pinterest', models.URLField(blank=True, max_length=10000, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
