# Generated by Django 3.2.11 on 2022-08-08 13:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_and_publication', '0001_initial'),
        ('home', '0001_initial'),
        ('core_functions', '0001_initial'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepublicationandresearch',
            name='publications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research_and_publication.publicationpage'),
        ),
        migrations.AddField(
            model_name='homepagepublicationandresearch',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research_and_publication.researchpage'),
        ),
        migrations.AddField(
            model_name='homepagecorefunctionorderable',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_functions.corefunction'),
        ),
        migrations.AddField(
            model_name='homepagecorefunctionorderable',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='homepageactivitiesorderable',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitypage'),
        ),
        migrations.AddField(
            model_name='homepageactivitiesorderable',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='functions_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a core function index page to link to for the Call to Action(normally some index page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_functions.corefunctionindexpage', verbose_name='Core Function Index CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
    ]
