# Generated by Django 3.2.11 on 2022-08-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('stats', '0001_initial'),
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='statistics_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a statistics page to link to for the Call to Action(normally some index page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stats.statisticsindexpage', verbose_name='Statistics CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='statistics_image',
            field=models.ForeignKey(blank=True, help_text='Choose an image to show alongside statistics text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Statistics image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='struct_org_image',
            field=models.ForeignKey(blank=True, help_text='A photo of the facility. This photo will be cropped to 1:1, 4:3, and 16:9 aspect ratios automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo of Organization'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='struct_org_logo',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use the logo in Settings > Layout > Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organization logo'),
        ),
    ]
